# Copyright Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.xpuExporter.name }}-daemonset
  namespace: {{ .Values.basic.namespace }}
  labels:
    app: {{ .Values.xpuExporter.name }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.xpuExporter.name }}
      app: {{ .Values.xpuExporter.name }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: {{ .Values.xpuExporter.name }}
        app: {{ .Values.xpuExporter.name }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      {{- with .Values.gpu.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      hostNetwork: true
      containers:
      - name: {{ .Values.xpuExporter.name }}
        env:
        - name: HTTPS_ENABLE
          value: {{ .Values.xpuExporter.https }}
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: {{ .Values.basic.swr_addr }}/{{ .Values.xpuExporter.image.name }}:{{ .Values.xpuExporter.image.version }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- with .Values.xpuExporter.args }}
        args:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.flavor.xpu_exporter_daemonset }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: xpu-log
          mountPath: /var/log/xpu
        - name: xpu-sock
          mountPath: /var/lib/xpu
        - name: tls-secret
          mountPath: /opt/xpu/certs
          readOnly: true
      volumes:
      - name: xpu-log
        hostPath:
          type: DirectoryOrCreate
          path: /var/log/xpu
      - name: xpu-sock
        hostPath:
          path: /var/lib/xpu
      - name: tls-secret
        secret:
          secretName: exporter-tls
          optional: true