# Copyright (C) Huawei Technologies Co., Ltd. 2024-2024. All rights reserved.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.devicePluginName }}-service-account
  namespace: {{ .Values.basic.namespace }}
  labels:
    name: {{ .Values.devicePluginName }}